# Generated by Django 6.1 on 2026-08-09 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_alter_item_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='badge',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('best_seller', 'Best Seller'), ('limited', 'Limited')], help_text='Optional label shown on the corner of the card. Sold pieces never show one.', max_length=20),
        ),
    ]
