# Generated by Django 6.1 on 2026-08-10 06:58

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_item_badge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='item_images/', validators=[core.validators.validate_image_upload]),
        ),
    ]
