# Generated by Django 6.1 on 2026-08-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_alter_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='item_images/thumbs/'),
        ),
    ]
