# Generated by Django 6.1 on 2026-08-10 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image', models.ImageField(blank=True, help_text='Landing page banner. Landscape, at least 1600px wide. Leave empty to show a placeholder instead.', upload_to='site/')),
                ('hero_image_alt', models.CharField(blank=True, help_text='Describes the photo for screen readers and when it fails to load.', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site content',
                'verbose_name_plural': 'Site content',
            },
        ),
    ]
