# Generated by Django 6.1 on 2026-08-10 06:58

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecontent',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Landing page banner. Landscape, at least 1600px wide. Leave empty to show a placeholder instead.', upload_to='site/', validators=[core.validators.validate_image_upload]),
        ),
    ]
