# Generated by Django 6.1 on 2026-08-17 09:15

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_sitecontent_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='studio_image',
            field=models.ImageField(blank=True, help_text='The tall image beside “Why us” on the home page. Portrait, around 1200 × 1600 — pieces laid out on stone or linen. Leave empty to show a placeholder instead.', upload_to='site/', validators=[core.validators.validate_image_upload]),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='studio_image_alt',
            field=models.CharField(blank=True, help_text='Describes the photo for screen readers and when it fails to load.', max_length=200),
        ),
    ]
