"""
Django settings for chainreaction project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


def env_bool(name, default=False):
    return os.environ.get(name, str(default)).strip().lower() in {'1', 'true', 'yes', 'on'}


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-)ys44@fh+j^x5!(b=ov!c#s*e8bg7dvb*eld+vcypt_%zt#+05',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DJANGO_DEBUG', True)
TESTING = 'test' in sys.argv

ALLOWED_HOSTS = [h for h in os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',') if h]

# Bila must be able to POST the webhook to us over HTTPS.
CSRF_TRUSTED_ORIGINS = [o for o in os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '').split(',') if o]

if not DEBUG:
    SECURE_SSL_REDIRECT = env_bool('DJANGO_SECURE_SSL_REDIRECT', True)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    # HSTS is hard to undo — leave at 0 until HTTPS is confirmed working.
    SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', 0))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = bool(SECURE_HSTS_SECONDS)
    SECURE_HSTS_PRELOAD = bool(SECURE_HSTS_SECONDS)
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'item',
    'dashboard',
    'cart',
    'orders',
]

# --- Email ---------------------------------------------------------------------
# Dev prints receipts to the console; set EMAIL_HOST to send for real.
SITE_URL = os.environ.get('SITE_URL', 'http://127.0.0.1:8000')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'Chain Reaction <orders@chainreaction.test>')
EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = env_bool('EMAIL_USE_TLS', True)
# 10s was not enough on a flaky link: a seller alert was lost to a timeout.
EMAIL_TIMEOUT = int(os.environ.get('EMAIL_TIMEOUT', 30))
EMAIL_BACKEND = os.environ.get(
    'EMAIL_BACKEND',
    'django.core.mail.backends.smtp.EmailBackend' if EMAIL_HOST
    else 'django.core.mail.backends.console.EmailBackend',
)

# Where customer replies should land. The DEFAULT_FROM_EMAIL address is
# send-only on Resend, so replying to a receipt would otherwise bounce.
# Falls back to the first ORDER_NOTIFY_EMAIL, then to the from-address.
REPLY_TO_EMAIL = os.environ.get('REPLY_TO_EMAIL', '').strip()

# Who gets told a paid order has landed. Comma-separated for more than one.
ORDER_NOTIFY_EMAILS = [
    address.strip()
    for address in os.environ.get('ORDER_NOTIFY_EMAIL', '').split(',')
    if address.strip()
]

# --- Bila payments (https://docs.usebila.com) ---------------------------------
# Sandbox: https://sandbox.usebila.com with an sk_test_ key.
BILA_BASE_URL = os.environ.get('BILA_BASE_URL', 'https://sandbox.usebila.com')
BILA_API_KEY = os.environ.get('BILA_API_KEY', '')
BILA_WALLET_ID = os.environ.get('BILA_WALLET_ID', '')
BILA_WEBHOOK_SECRET = os.environ.get('BILA_WEBHOOK_SECRET', '')
BILA_COUNTRY = os.environ.get('BILA_COUNTRY', 'zm')
BILA_FEE_BEARER = os.environ.get('BILA_FEE_BEARER', 'merchant')  # merchant | customer

# ── Rate limiting ─────────────────────────────────────────────────────────────
# Off during tests so fixtures can hit a view repeatedly; the dedicated
# rate-limit tests turn it back on explicitly.
RATELIMIT_ENABLE = env_bool('RATELIMIT_ENABLE', not TESTING)
# LocMemCache is per-process, so with N gunicorn workers a limit is effectively
# N times looser. Point CACHE_URL at Redis, or lean on Cloudflare, once that
# matters. Good enough to stop the obvious abuse today.
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'chainreaction',
    }
}

# Shared secret for the reconciliation endpoint an external scheduler calls.
# Blank disables the endpoint entirely.
CRON_TOKEN = os.environ.get('CRON_TOKEN', '')

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.RateLimitMiddleware',
]

ROOT_URLCONF = 'chainreaction.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'cart.context_processors.cart_context_processor',
            ],
        },
    },
]

WSGI_APPLICATION = 'chainreaction.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=f'sqlite:///{BASE_DIR / "db.sqlite3"}',
        conn_max_age=600,
        conn_health_checks=True,
        # sqlite has no sslmode option — a sqlite DATABASE_URL (persistent-disk
        # VM) must not get ssl_require or every connection raises TypeError.
        ssl_require=not DEBUG
        and bool(os.environ.get('DATABASE_URL'))
        and not os.environ.get('DATABASE_URL', '').startswith('sqlite'),
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Lusaka'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static'] if (BASE_DIR / 'static').exists() else []

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ── Media storage ─────────────────────────────────────────────────────────────
# Cloudflare R2 when configured, local disk otherwise. On a hosted box the
# local disk is wiped by every redeploy, so R2 is required before launch.
R2_ACCESS_KEY_ID = os.environ.get('R2_ACCESS_KEY_ID', '')
R2_SECRET_ACCESS_KEY = os.environ.get('R2_SECRET_ACCESS_KEY', '')
R2_BUCKET_NAME = os.environ.get('R2_BUCKET_NAME', '')
R2_ENDPOINT_URL = os.environ.get('R2_ENDPOINT_URL', '')
# Public read URL for the bucket, e.g. https://media.chainreactionjewelry.site
R2_PUBLIC_URL = os.environ.get('R2_PUBLIC_URL', '').rstrip('/')

USE_R2 = bool(R2_ACCESS_KEY_ID and R2_SECRET_ACCESS_KEY and R2_BUCKET_NAME and R2_ENDPOINT_URL)

if USE_R2:
    _media_storage = {
        'BACKEND': 'storages.backends.s3.S3Storage',
        'OPTIONS': {
            'bucket_name': R2_BUCKET_NAME,
            'endpoint_url': R2_ENDPOINT_URL,
            'access_key': R2_ACCESS_KEY_ID,
            'secret_key': R2_SECRET_ACCESS_KEY,
            'region_name': 'auto',          # R2 has no regions
            'signature_version': 's3v4',
            'default_acl': None,            # R2 rejects ACLs outright
            'querystring_auth': False,      # bucket is served publicly
            'file_overwrite': False,        # keep old files if a name repeats
            # Serve through the custom domain so bytes come from Cloudflare's
            # edge rather than the bucket endpoint.
            'custom_domain': R2_PUBLIC_URL.split('://')[-1] or None,
        },
    }
else:
    _media_storage = {'BACKEND': 'django.core.files.storage.FileSystemStorage'}

STORAGES = {
    'default': _media_storage,
    # Compresses and fingerprints static files so they can be cached forever.
    # The manifest backend requires collectstatic to have run, which is not true
    # under tests or in dev, so it is production-only.
    'staticfiles': {
        'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage'
        if DEBUG or TESTING
        else 'whitenoise.storage.CompressedManifestStaticFilesStorage'
    },
}

# Reject oversized uploads before they reach a form. A phone photo is ~5MB;
# anything past this is either a mistake or an attack.
MAX_UPLOAD_BYTES = int(os.environ.get('MAX_UPLOAD_BYTES', 8 * 1024 * 1024))
DATA_UPLOAD_MAX_MEMORY_SIZE = MAX_UPLOAD_BYTES + 1024 * 1024

# Logging. Without this every logger.exception in the payment path is silently
# discarded, which would make a failed payment invisible.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {'format': '{asctime} {levelname} {name} {message}', 'style': '{'},
    },
    'handlers': {
        'console': {'class': 'logging.StreamHandler', 'formatter': 'standard'},
    },
    'root': {'handlers': ['console'], 'level': 'INFO'},
    'loggers': {
        'django': {'handlers': ['console'], 'level': 'INFO', 'propagate': False},
        # The money paths stay verbose whatever else is turned down.
        'orders': {'handlers': ['console'], 'level': 'INFO', 'propagate': False},
        'django.security': {'handlers': ['console'], 'level': 'INFO', 'propagate': False},
    },
}

# Shown on the legal pages. Bump it whenever you change their wording.
LEGAL_UPDATED = os.environ.get('LEGAL_UPDATED', '10 August 2026')

# ── Error monitoring ──────────────────────────────────────────────────────────
SENTRY_DSN = os.environ.get('SENTRY_DSN', '')
if SENTRY_DSN:
    import sentry_sdk

    sentry_sdk.init(
        dsn=SENTRY_DSN,
        environment=os.environ.get('SENTRY_ENVIRONMENT', 'production' if not DEBUG else 'local'),
        traces_sample_rate=float(os.environ.get('SENTRY_TRACES_SAMPLE_RATE', 0.1)),
        # Never ship customer phone numbers or addresses to a third party.
        send_default_pii=False,
    )
